export function getShorthandHelpLines(): string[] {
  return [
    'Keybindings:',
    '',
    'Navigation:',
    '  j/k or ↑/↓ = move',
    '  g/G = top/bottom',
    '  Ctrl+U / Ctrl+D (or PgUp/PgDn) = page up/down',
    '  h/l or ←/→ = previous/next view',
    '  0–9 = jump to view',
    '  : = go to line (task list)',
    '  Enter = fold/unfold (area/project header or task with subtasks)',
    '  z = show/hide done tasks',
    '  q = quit',
    '  Ctrl+C twice = quit (even if UI is busy)',
    '',
    'Search:',
    '  / = search (starts in view scope)',
    '  Ctrl+/ or ! = toggle view/global scope',
    '  Enter = apply search',
    '  Esc = cancel search',
    '',
    'Task actions:',
    '  space/x = toggle done',
    '  p = set priority',
    '  b = set bucket',
    '  n = toggle now (working)',
    '  t = set plan',
    '  d = set due',
    '  e = edit (t=text, m=metadata)',
    '  a = add task (Tab switches project target)',
    '  r = remove task (deletes subtree)',
    '',
    'Projects view:',
    '  type = filter projects',
    '  ↑/↓ = move (projects list)',
    '  Enter = open project',
    '  Ctrl+N = add project',
    '  Esc/Backspace = back (from project drilldown)',
    '',
    'Row shorthands (visual hints in the task list):',
    '',
    'Priority:',
    '  (A) = high',
    '  (B) = normal',
    '  (C) = low',
    '',
    'Bucket:',
    '  * = now (working)',
    '  ! = today',
    '  > = upcoming',
    '  ~ = anytime',
    '  ? = someday',
    '',
    'Notes:',
    '  - These are display shorthands; canonical metadata lives in [..] (priority:, bucket:, plan:, due:, etc.)',
  ];
}
