export function getShorthandHelpLines(): string[] {
  return [
    'Keybindings:',
    '',
    'Navigation:',
    '  j/k or ↑/↓ = move',
    '  g/G = top/bottom',
    '  Ctrl+U / Ctrl+D (or PgUp/PgDn) = page up/down',
    '  0–9 = jump to view',
    '  : = go to line (task list)',
    '  h or ← = collapse (or go to parent)',
    '  l or → = expand (or go to first child)',
    '  F = fold/unfold everything',
    '  z = show/hide done tasks',
    '  o = toggle priority ordering (high-first / low-first / off)',
    '  q = quit',
    '  Ctrl+C twice = quit (even if UI is busy)',
    '',
    'Search:',
    '  / = search (starts in view scope)',
    '  Ctrl+/ = toggle view/global scope',
    '  Enter = apply search',
    '  Esc = cancel search',
    '',
    'Task actions:',
    '  space/x = toggle done',
    '  p = set priority',
    '  b = set bucket',
    '  n = toggle now ↔ today',
    '  P = set plan',
    '  t/! = toggle bucket today',
    '  u/> = toggle bucket upcoming',
    '  y/~ = toggle bucket anytime',
    '  s = toggle bucket someday',
    '  d = set due',
    '  e = edit (t=text, m=metadata)',
    '  a = add task (Text first; Tab/Shift+Tab moves fields)',
    '  r = remove task (deletes subtree)',
    '',
    'Projects view:',
    '  / = filter projects',
    '  type = filter (when active)',
    '  j/k or ↑/↓ = move (projects list)',
    '  Enter = open project',
    '  Ctrl+N = add project',
    '  Esc/Backspace = back (from project drilldown)',
    '',
    'Row shorthands (visual hints in the task list):',
    '',
    'Priority:',
    '  (A) = high',
    '  (B) = normal',
    '  (C) = low',
    '',
    'Bucket:',
    '  * = now (working)',
    '  ! = today',
    '  > = upcoming',
    '  ~ = anytime',
    '  ? = someday',
    '',
    'Notes:',
    '  - These are display shorthands; canonical metadata lives in [..] (priority:, bucket:, plan:, due:, etc.)',
  ];
}
